### ISSUE TITLE
Possible defect for method 'object_exists'

### ISSUE THREAD

**Issue by OshinoMoumou** [veltzer/pyawskit#1]
Greetings!
I noticed that method object_exists referred a StackOverflow post, while [a recent comment](https://stackoverflow.com/questions/33842944/check-if-a-key-exists-in-a-bucket-in-s3-using-boto3#comment113830445_33843019) to it mentioned that the method can cause a problem if the file is huge.
I'm trying to learn the usefulness of such small updates on StackOverflow. Would this comment help improve your code? I understand that such defect might not happen in real life situation. In that case, do you think this comment can help prevent future bugs (for example, when the code were reused somewhere else)?
I'll really appreciate it if you could kindly give me some feedback or suggestions. Thank you very much for your time.
Have a nice day!

**Comment by veltzer** [comment]
fixed it in the new version
